[package]
name = "worker-pool"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
chromiumoxide.workspace = true
config = { path = "../config" }
dom-engine = { path = "../dom-engine" }
network-engine = { path = "../network-engine" }
futures.workspace = true
regex.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tempfile.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
types = { path = "../types" }
url.workspace = true
artifact-store = { path = "../artifact-store" }
companion-protocol = { path = "../companion-protocol" }

[dev-dependencies]
test-site = { path = "../test-site" }
