use types::PageId;

/// Returns a self-contained, read-only DOM projection. The result is JSON text so
/// Chromium CDP and Firefox BiDi apply identical serialization semantics.
pub fn form_snapshot_expression(page_id: &PageId) -> String {
    let page_id = serde_json::to_string(page_id).expect("page IDs serialize");
    FORM_SNAPSHOT_SCRIPT.replace("__PAGE_ID__", &page_id)
}

const FORM_SNAPSHOT_SCRIPT: &str = r#"JSON.stringify((()=>{
const clip=(v,n)=>{let s=String(v??'').replace(/[\u0000-\u001f\u007f-\u009f]/gu,' ');const enc=new TextEncoder();let bytes=enc.encode(s).length;while(bytes>n&&s){s=s.slice(0,Math.max(0,Math.floor(s.length*n/bytes)));bytes=enc.encode(s).length}return s};
const text=(v,n=2048)=>{const s=clip(v,n).trim().replace(/\s+/gu,' ');return s||null};
const controls=[...document.querySelectorAll('input,textarea,select,button,[contenteditable="true"],[role="switch"],[role="combobox"],[role="listbox"]')];
const forms=[...document.forms].slice(0,64);const formIds=new Map(forms.map((e,i)=>[e,`form-${i}`]));
const eligibleControls=controls.filter(e=>!e.form||formIds.has(e.form));let truncated=document.forms.length>64||eligibleControls.length>512||eligibleControls.length!==controls.length;let optionCount=0;
const visibleControls=eligibleControls.slice(0,512);const controlIds=new Map(visibleControls.map((e,i)=>[e,`control-${i}`]));
const label=e=>text(e.getAttribute('aria-label'))||text((e.getAttribute('aria-labelledby')||'').split(/\s+/).filter(Boolean).map(id=>document.getElementById(id)?.textContent||'').join(' '))||text(e.labels?.[0]?.textContent)||text(e.closest('label')?.textContent)||text(e.getAttribute('placeholder'));
const role=e=>{const explicit=text(e.getAttribute('role'));if(explicit)return explicit;const tag=e.tagName.toLowerCase(),type=String(e.type||e.getAttribute('type')||'text').toLowerCase();if(tag==='button'||['submit','reset','button'].includes(type))return 'button';if(type==='checkbox')return 'checkbox';if(type==='radio')return 'radio';if(tag==='select')return e.multiple?'listbox':'combobox';if(tag==='textarea'||e.isContentEditable)return 'textbox';return type==='range'?'slider':'textbox'};
const kind=e=>{const tag=e.tagName.toLowerCase(),type=String(e.type||e.getAttribute('type')||'text').toLowerCase(),r=e.getAttribute('role');if(r==='switch')return'switch';if(r==='combobox')return'combobox';if(r==='listbox')return'listbox';if(e.isContentEditable)return'contentEditable';if(tag==='button')return type==='reset'?'reset':type==='button'?'other':'submit';if(tag==='select')return e.multiple?'selectMultiple':'selectOne';if(tag==='textarea')return'text';return ({text:'text',email:'email',password:'password',search:'search',number:'number',checkbox:'checkbox',radio:'radio',date:'date',time:'time','datetime-local':'dateTimeLocal',range:'range',file:'file',submit:'submit',reset:'reset'})[type]||'other'};
const names=new Map();for(const e of visibleControls){const k=`${role(e)}\0${label(e)||''}`;names.set(k,(names.get(k)||0)+1)}const seen=new Map();
const describe=e=>{const k=kind(e),tag=e.tagName.toLowerCase(),editableCombo=k==='combobox'&&(tag==='input'||tag==='textarea'||e.isContentEditable),name=label(e),rk=`${role(e)}\0${name||''}`,ordinal=seen.get(rk)||0;seen.set(rk,ordinal+1);const target=name?{role:role(e),accessibleName:name,...(names.get(rk)>1?{ordinal}:{}),framePath:[],shadowPath:[]}:null;const selected=e.tagName==='SELECT'?[...e.selectedOptions].map(o=>clip(o.value,4096)):[];let state;if(k==='password')state={kind:'redacted',present:Boolean(e.value)};else if(k==='checkbox'||k==='radio'||k==='switch')state={kind:'checked',checked:Boolean(e.checked||e.getAttribute('aria-checked')==='true')};else if(k==='selectOne'||k==='selectMultiple'||k==='listbox'||(k==='combobox'&&!editableCombo))state={kind:'selection',values:selected};else if(k==='file'){const count=e.files?.length||0;if(count>512)truncated=true;state={kind:'files',count:Math.min(count,512)}}else state=e.value||e.textContent?{kind:'text',value:clip(e.value??e.textContent??'',4096)}:{kind:'empty'};
const v=e.validity||{},flags=[['valueMissing','valueMissing'],['typeMismatch','typeMismatch'],['patternMismatch','patternMismatch'],['tooLong','tooLong'],['tooShort','tooShort'],['rangeUnderflow','rangeUnderflow'],['rangeOverflow','rangeOverflow'],['stepMismatch','stepMismatch'],['badInput','badInput'],['customError','customError']].filter(([p])=>v[p]).map(([,n])=>n);const described=k==='password'?[]:(e.getAttribute('aria-describedby')||'').split(/\s+/).filter(Boolean).slice(0,512).map(id=>text(document.getElementById(id)?.textContent)).filter(Boolean);
let opts=[];if(e.options){for(const o of [...e.options]){if(optionCount++>=512){truncated=true;break}const group=o.parentElement?.tagName==='OPTGROUP'?o.parentElement:null;opts.push({value:clip(o.value,4096),label:clip(o.label||o.textContent||'',2048),disabled:Boolean(o.disabled||group?.disabled),selected:Boolean(o.selected),groupLabel:text(group?.label)})}}
let ops=['clear'];if(['text','email','password','search','number','date','time','dateTimeLocal','range','contentEditable'].includes(k)||editableCombo)ops.unshift('setText');else if(['checkbox','radio','switch'].includes(k))ops.unshift('setChecked');else if(['selectOne','combobox'].includes(k))ops.unshift('selectOne');else if(['selectMultiple','listbox'].includes(k))ops.unshift('selectMany');else if(k==='file')ops.unshift('setFiles');else if(['submit','reset'].includes(k)||tag==='button'||(tag==='input'&&e.type==='button'))ops=['activate'];
const owner=e.form&&formIds.has(e.form)?formIds.get(e.form):null,fieldset=e.closest('fieldset'),fieldsetIndex=fieldset&&owner?[...e.form.querySelectorAll('fieldset')].indexOf(fieldset):-1,minLength=Number.isInteger(e.minLength)&&e.minLength>=0?e.minLength:null,maxLength=Number.isInteger(e.maxLength)&&e.maxLength>=0?e.maxLength:null;return{id:controlIds.get(e),formId:owner,groupId:fieldsetIndex>=0?`${owner}-group-${fieldsetIndex}`:null,target,controlKind:k,accessibleName:name,label:text(e.labels?.[0]?.textContent),description:described[0]||null,placeholder:text(e.getAttribute('placeholder')),autocomplete:text(e.getAttribute('autocomplete')),state,constraints:{required:Boolean(e.required),readOnly:Boolean(e.readOnly),disabled:Boolean(e.matches(':disabled')||e.getAttribute('aria-disabled')==='true'),pattern:text(e.getAttribute('pattern')),minLength:minLength!==null&&maxLength!==null&&minLength>maxLength?null:minLength,maxLength,min:text(e.getAttribute('min')),max:text(e.getAttribute('max')),step:text(e.getAttribute('step')),multiple:Boolean(e.multiple),accept:(e.getAttribute('accept')||'').split(',').map(x=>text(x)).filter(Boolean).slice(0,128)},validity:{willValidate:Boolean(e.willValidate),valid:v.valid!==false,flags,message:k==='password'?null:text(e.validationMessage,1024),describedBy:described},options:opts,supportedOperations:ops}};
const all=visibleControls.map(describe);const descriptors=forms.map((f,i)=>{const id=formIds.get(f),owned=all.filter(c=>c.formId===id),fieldsets=[...f.querySelectorAll('fieldset')].slice(0,128);if(f.querySelectorAll('fieldset').length>128)truncated=true;const groups=fieldsets.map((g,j)=>({id:`${id}-group-${j}`,label:text(g.querySelector(':scope > legend')?.textContent),description:null,controlIds:owned.filter(c=>c.groupId===`${id}-group-${j}`).map(c=>c.id)}));const invalid=owned.filter(c=>!c.validity.valid).map(c=>c.id);return{id,target:null,accessibleName:text(f.getAttribute('aria-label'))||text(f.getAttribute('name')),description:null,groups,controls:owned,submitControlIds:owned.filter(c=>c.controlKind==='submit').map(c=>c.id),resetControlIds:owned.filter(c=>c.controlKind==='reset').map(c=>c.id),validity:{valid:invalid.length===0,invalidControlIds:invalid}}});
return{schemaVersion:1,pageId:__PAGE_ID__,forms:descriptors,unownedControls:all.filter(c=>!c.formId),truncated};})())"#;
