[package]
name = "runtime-tests"
version.workspace = true
edition.workspace = true

[dependencies]
checkpoint-store = { path = "../checkpoint-store" }
chrono.workspace = true
config = { path = "../config" }
sdk-core = { path = "../sdk-core" }
page-runtime = { path = "../page-runtime" }
serde_json.workspace = true
tempfile.workspace = true
test-site = { path = "../test-site" }
tokio.workspace = true
types = { path = "../types" }
workflow-journal = { path = "../workflow-journal" }
worker-pool = { path = "../worker-pool" }
