[package]
name = "intent-engine"
version.workspace = true
edition.workspace = true

[dependencies]
async-trait.workspace = true
dom-engine = { path = "../dom-engine" }
hex.workspace = true
sha2.workspace = true
thiserror.workspace = true
types = { path = "../types" }

[dev-dependencies]
tokio.workspace = true
