[package]
name = "intent-engine"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
async-trait.workspace = true
base64.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
dom-engine = { path = "../dom-engine", version = "0.13.0" }
hex.workspace = true
sha2.workspace = true
thiserror.workspace = true
tokio.workspace = true
url.workspace = true
tracing.workspace = true
observability = { path = "../observability", version = "0.13.0" }
types = { path = "../types", version = "0.13.0" }
context-store = { path = "../context-store", version = "0.13.0" }

[dev-dependencies]
tempfile.workspace = true
