[package]
name = "broker"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
axum.workspace = true
base64.workspace = true
chrono.workspace = true
getrandom.workspace = true
hex.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tokio.workspace = true
tower.workspace = true
url.workspace = true
uuid.workspace = true
types = { path = "../types" }
sdk-core = { path = "../sdk-core" }
config = { path = "../config" }
interface-core = { path = "../interface-core" }
artifact-store = { path = "../artifact-store" }

[dev-dependencies]
futures-util.workspace = true
interface-conformance = { path = "../interface-conformance" }
tempfile.workspace = true
