[package]
name = "workflow-journal"
version.workspace = true
edition.workspace = true

[dependencies]
async-trait.workspace = true
chrono.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
types = { path = "../types" }

[dev-dependencies]
tempfile.workspace = true
