[package]
name = "session-manager"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
chrono.workspace = true
tokio.workspace = true
tracing.workspace = true
types = { path = "../types", version = "0.11.1" }
worker-pool = { path = "../worker-pool", version = "0.11.1" }

[dev-dependencies]
async-trait.workspace = true
