[package]
name = "session-manager"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
chrono.workspace = true
tokio.workspace = true
tracing.workspace = true
types.workspace = true
worker-pool.workspace = true

[dev-dependencies]
async-trait.workspace = true
